import { PokemonList } from "./pokemon.models";

export const POKEMON_LIST: PokemonList =[
{
    id:1,
    name:'Squirtle',
      life:25,
    picture:'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/025.png',
    domage:5,
    types:['Feu'],
    created: new Date(),
},
{
    id:2,
    name:'Bulbisarre',
      life:25,
    picture:'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/005.png',
    domage:5,
    types:['Eau'],
    created: new Date(),
},
{
    id:3,
    name:'Carapus',
      life:25,
    picture:'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/007.png',
    domage:5,
    types:['plante', ],
    created: new Date(),
},
{
    id:4,
    name:'Rattata',
      life:25,
    picture:'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/008.png',
    domage:5,
    types:['Electrik'],
    created: new Date(),
},
{
    id:5,
    name:'Rondoudou',
      life:25,
    picture:'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/009.png',
    domage:5,
    types:['plante'],
    created: new Date(),
},
{
    id:6,
    name:'Blaz',
      life:25,
    picture:'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/001.png',
    domage:5,
    types:['Vol'],
    created: new Date(),
},
{
    id:7,
    name:'rocoue',
      life:25,
    picture:'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/003.png',
    domage:5,
    types:['Fée'],
    created: new Date(),
},
{
    id:8,
    name:'Boss',
      life:25,
    picture:'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/010.png',
    domage:5,
    types:['Insecte'],
    created: new Date(),
},
{
    id:9,
    name:'Lugia',
      life:25,
    picture:'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/015.png',
    domage:5,
    types:['Poison'],
    created: new Date(),
},
{
    id:10,
    name:'Nidoran',
      life:25,
    picture:'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/019.png',
    domage:5,
    types:['plante'],
    created: new Date(),
},
{
    id:11,
    name:'Hoothoot',
      life:25,
    picture:'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/030.png',
    domage:5,
    types:['Fée'],
    created: new Date(),
},
{
    id:12,
    name:'Snorlax',
      life:25,
    picture:'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/021.png',
    domage:5,
    types:['Electrik'],
    created: new Date(),
}]
